<?php
$title = 'Add new blogpost';
$this->headTitle($title);
print $this->showMessages();
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('blog', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('text'));
echo $this->formRow($form->get('state'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();